### ISSUE TITLE
Pan out of current extent issue

### ISSUE THREAD

**Issue by geoderek** [nemac/seldon#68]
To recreate:
1. Load up default view
2. Using the zoom tool Zoom to small geographic area e.g. city or county
3. Toggle on/off default NDVI layer
4. Using the pan tool pan completely out of the small geographic area to

**Comment by frimmel** [comment]
This issue is still present if the map is loaded in with a small extent via a shareurl. To recreate this you can go to the following link & pan outside of the initial bounding box -- no new content will be loaded.

http://forwarn.forestthreats.org/fcav2/?theme=CONUS_Vegetation_Monitoring_Tools&layers=AD,AAB&mask=Forest&alphas=1,1&accgp=G04&basemap=Streets&extent=-9407065.1510648,4485324.0905694,-9274141.158877,4553811.6679128

**Comment by geoderek** [comment]
Yep I just verified this on Chrome and Firefox.  

http://forwarn.forestthreats.org/fcav2/?theme=MODIS_Phenology_Parameters_Products&layers=PARAMGREENSTART,AF,AAB&mask=Forest&alphas=1,1,1&accgp=G04&basemap=Streets&extent=-9548080.1193757,4068271.4196238,-9546474.9417819,4069010.7090066

So the same fix need to occur with the path of sharing a url.
